# Dependencies
markdown: redcarpet
hightlighter: pygments
gems:
  - jekyll-paginate

# Permalinks
permalink: pretty

# Setup
title: Project 415x
tagline: A Linear Algebra Experience
description: Project 415x is a learning tool for students to have a direct visual and kinesthetic experience of core concepts in Linear Algebra
keywords: Project, 415x, Mathematics, Linear, Algebgra, UIUC, Illinois, Engineering, STEM
url: http://p415x.xyz
baseurl: /
paginate: 5
paginate_path: 'blog/page:num'
paginate_base: '/blog/'
sass:
  style: :compressed

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# Author
author:
  name: Joseph Milla
  url: https://twitter.com/josephmilla
  email: joseph@milla.xyz

# Version
version: 0.0.0
